"""empty message

Revision ID: 696a561b2b81
Revises: d0513ec4282b
Create Date: 2022-12-08 10:31:29.055737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696a561b2b81'
down_revision = 'd0513ec4282b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
