"""empty message
Revision ID: 9060651e3eef
Revises: 
Create Date: 2022-12-01 21:06:36.800433
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9060651e3eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'start',
                    existing_type=mysql.INTEGER(),
                    nullable=True)
    op.alter_column('alerts', 'event',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('alerts', 'message',
                    existing_type=mysql.VARCHAR(length=512),
                    nullable=True)
    op.alter_column('alerts', 'hash',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.drop_index('ix_alerts_id', table_name='alerts')
    op.drop_column('alerts', 'end')
    op.alter_column('locations', 'city',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('locations', 'state',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=True)
    op.drop_index('ix_locations_id', table_name='locations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.alter_column('locations', 'state',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('locations', 'city',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.add_column('alerts', sa.Column('end', mysql.INTEGER(),
                  autoincrement=False, nullable=False))
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    op.alter_column('alerts', 'hash',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('alerts', 'message',
                    existing_type=mysql.VARCHAR(length=512),
                    nullable=False)
    op.alter_column('alerts', 'event',
                    existing_type=mysql.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('alerts', 'start',
                    existing_type=mysql.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
