"""empty message

Revision ID: 9dc6d36efd85
Revises: fb222616e0b6
Create Date: 2022-12-01 21:24:35.233556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc6d36efd85'
down_revision = 'fb222616e0b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
