"""empty message

Revision ID: d0513ec4282b
Revises: 9dc6d36efd85
Create Date: 2022-12-03 12:26:08.953738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0513ec4282b'
down_revision = '9dc6d36efd85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_constraint('alerts_ibfk_1', 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'location', ['location_id'], ['id'], ondelete='CASCADE')
    op.add_column('location', sa.Column('subscription_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'subscription_count')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_ibfk_1', 'alerts', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_table('locations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
