"""empty message

Revision ID: fb222616e0b6
Revises: 9060651e3eef
Create Date: 2022-12-01 21:11:19.741874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb222616e0b6'
down_revision = '9060651e3eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('end', sa.Integer(), nullable=True))
    op.alter_column('alerts', 'event',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('alerts', 'message',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('alerts', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('locations', sa.Column('country', sa.String(length=255), nullable=False))
    op.alter_column('locations', 'city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('locations', 'state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'state',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('locations', 'city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('locations', 'country')
    op.alter_column('alerts', 'hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('alerts', 'message',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('alerts', 'event',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('alerts', 'end')
    # ### end Alembic commands ###
